# Legacy remote backups
- /bak/

# Directories
- .AppleDouble/
- .Spotlight-V100/
- .TemporaryItems/
- .Trashes/
- .Trash-*/
- .fseventsd/
- .git/
- .venv/
- __pycache__/
- node_modules/

# Files
- .DS_Store
- ._*
- .LSOverride
- .apdisk
- Icon\r
- Thumbs.db
- Thumbs.db:encryptable
- desktop.ini
- ehthumbs.db
- ehthumbs_vista.db
- ~$*
- ~*.tmp
- *.tmp
- .*.swp
- .*.swo
- *~
