#!/bin/zsh
# niclake.me/mac-displaylink

screen -wipe >/dev/null 2>&1 || true

exec script -q /dev/null /usr/bin/screen -dmS alttab /usr/bin/arch -arm64 /Applications/AltTab.app/Contents/MacOS/AltTab
